const designCss=document.createElement('link');designCss.rel='stylesheet';designCss.href='design2.css?v=20260820a';document.head.appendChild(designCss);

const menuBtn=document.querySelector('.menu-btn');const nav=document.querySelector('.nav');if(menuBtn){menuBtn.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuBtn.setAttribute('aria-expanded',open)})}document.querySelectorAll('.nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();

const resultSlider=document.querySelector('.result-slider');if(resultSlider){const slides=[...resultSlider.querySelectorAll('.result-slide')],dots=[...resultSlider.querySelectorAll('.slider-dots button')],counter=resultSlider.querySelector('.slider-counter b'),prev=resultSlider.querySelector('.slider-prev'),next=resultSlider.querySelector('.slider-next');let current=0,timer,startX=0;const show=i=>{current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('active',n===current));dots.forEach((d,n)=>d.classList.toggle('active',n===current));if(counter)counter.textContent=String(current+1).padStart(2,'0')};const restart=()=>{clearInterval(timer);timer=setInterval(()=>show(current+1),5200)};prev?.addEventListener('click',()=>{show(current-1);restart()});next?.addEventListener('click',()=>{show(current+1);restart()});dots.forEach((d,i)=>d.addEventListener('click',()=>{show(i);restart()}));resultSlider.addEventListener('touchstart',e=>startX=e.changedTouches[0].clientX,{passive:true});resultSlider.addEventListener('touchend',e=>{const diff=e.changedTouches[0].clientX-startX;if(Math.abs(diff)>45){show(diff>0?current-1:current+1);restart()}},{passive:true});restart()}

(()=>{
  const main=document.querySelector('main'),about=document.querySelector('.about'),salong=document.querySelector('#salongen'),priser=document.querySelector('#priser'),team=document.querySelector('#teamet'),resultat=document.querySelector('#resultat'),reviews=document.querySelector('.real-reviews'),why=document.querySelector('.why-us'),contact=document.querySelector('.contact'),careers=document.querySelector('.careers'),footerCta=document.querySelector('.footer-cta'),footer=document.querySelector('.site-footer');

  if(why)why.style.display='none';if(contact)contact.style.display='none';if(careers)careers.style.display='none';if(footerCta)footerCta.style.display='none';if(footer)footer.id='kontakt';
  if(main)[about,salong,priser,team,resultat,reviews].forEach(s=>{if(s)main.appendChild(s)});

  const labels=[['.about .section-tag','01 / VÄLKOMMEN'],['#salongen .section-tag','02 / SALONGEN'],['#priser .section-tag','03 / BEHANDLINGAR & PRISER'],['#teamet .section-tag','04 / TEAMET'],['#resultat .section-tag','05 / KUNDRESULTAT'],['.real-reviews .section-tag','06 / OMDÖMEN']];labels.forEach(([sel,text])=>{const el=document.querySelector(sel);if(el)el.textContent=text});

  // Mer intim hero med riktiga bilder från salongen.
  const hero=document.querySelector('.hero');
  if(hero&&!hero.querySelector('.hero-family-strip')){const strip=document.createElement('div');strip.className='hero-family-strip';['assets/salong-extra-01.jpg','assets/salong-extra-03.jpg','assets/salong-extra-05.jpg','assets/salong-extra-08.jpg'].forEach((src,i)=>{const img=document.createElement('img');img.src=src;img.alt='Salong Alexander miljö '+(i+1);strip.appendChild(img)});hero.appendChild(strip)}
  const heroText=document.querySelector('.hero-inner>p:last-of-type');if(heroText&&!document.querySelector('.hero-warmline')){const warm=document.createElement('p');warm.className='hero-warmline';warm.textContent='En personlig salong där du ska känna dig välkommen, sedd och omhändertagen.';heroText.insertAdjacentElement('afterend',warm)}

  // Prislistan: ren accordion, första kategorin öppen.
  [...document.querySelectorAll('.price-card')].forEach((card,i)=>{const title=card.querySelector('h3');if(!title)return;card.querySelector('.price-toggle')?.remove();const toggle=document.createElement('button');toggle.type='button';toggle.className='price-toggle';toggle.setAttribute('aria-expanded',i===0?'true':'false');toggle.innerHTML=`<span>${title.textContent}</span><b>${i===0?'−':'+'}</b>`;title.style.display='none';card.insertBefore(toggle,title.nextSibling);card.classList.toggle('price-collapsed',i!==0);toggle.addEventListener('click',()=>{const collapsed=card.classList.toggle('price-collapsed');toggle.setAttribute('aria-expanded',String(!collapsed));toggle.querySelector('b').textContent=collapsed?'+':'−'})});

  // Menyn prioriterar kundresan.
  document.querySelectorAll('.nav a:not(.btn)').forEach(a=>a.remove());
  const bookBtn=document.querySelector('.nav .btn');const links=[['Salongen','#salongen'],['Priser','#priser'],['Teamet','#teamet'],['Resultat','#resultat'],['Omdömen','.real-reviews'],['Kontakt','#kontakt']];links.forEach(([label,target])=>{const a=document.createElement('a');a.textContent=label;if(target.startsWith('.')){a.href='#omdomen';const r=document.querySelector(target);if(r)r.id='omdomen'}else a.href=target;nav?.insertBefore(a,bookBtn||null)});

  // Exakt en fungerande Jobba hos oss-länk + modal, så den fungerar även utan installerad mailapp.
  document.querySelectorAll('.site-footer a').forEach(a=>{if(a.textContent.toLowerCase().includes('jobba hos oss'))a.remove()});
  const quick=[...document.querySelectorAll('.footer-group')].find(g=>g.querySelector('h3')?.textContent.trim()==='Snabblänkar');
  if(quick){const job=document.createElement('a');job.href='#jobb-info';job.className='footer-careers-link';job.textContent='Jobba hos oss ↗';quick.appendChild(job);job.addEventListener('click',e=>{e.preventDefault();document.querySelector('.job-modal')?.classList.add('open')})}
  if(!document.querySelector('.job-modal')){const modal=document.createElement('div');modal.className='job-modal';modal.innerHTML=`<div class="job-modal-card" role="dialog" aria-modal="true" aria-label="Jobba hos oss"><button class="job-modal-close" aria-label="Stäng">×</button><p class="eyebrow accent">JOBBA HOS OSS</p><h3>Vill du bli en del av Salong Alexander?</h3><p>Är du frisör och intresserad av att arbeta hos oss? Skicka gärna en intresseanmälan till <strong>kontakt@salongalexander.se</strong>.</p><div class="job-modal-actions"><a class="btn" href="mailto:kontakt@salongalexander.se?subject=Intresseanmälan%20-%20Jobba%20hos%20Salong%20Alexander">Skicka intresseanmälan ↗</a><button class="btn-secondary" type="button">Kopiera e-post</button></div></div>`;document.body.appendChild(modal);modal.querySelector('.job-modal-close').addEventListener('click',()=>modal.classList.remove('open'));modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('open')});modal.querySelector('.btn-secondary').addEventListener('click',async e=>{try{await navigator.clipboard.writeText('kontakt@salongalexander.se');e.currentTarget.textContent='E-post kopierad ✓'}catch{e.currentTarget.textContent='kontakt@salongalexander.se'}})}
})();