const premiumCss=document.createElement("link");premiumCss.rel="stylesheet";premiumCss.href="mobile-premium.css?v=20260820b";document.head.appendChild(premiumCss);

const menuBtn=document.querySelector(".menu-btn");const nav=document.querySelector(".nav");if(menuBtn){menuBtn.addEventListener("click",()=>{const open=nav.classList.toggle("open");menuBtn.setAttribute("aria-expanded",open)})}document.querySelectorAll(".nav a").forEach(a=>a.addEventListener("click",()=>nav.classList.remove("open")));const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>observer.observe(el));document.getElementById("year").textContent=new Date().getFullYear();

const resultSlider=document.querySelector(".result-slider");if(resultSlider){const slides=[...resultSlider.querySelectorAll(".result-slide")];const dots=[...resultSlider.querySelectorAll(".slider-dots button")];const counter=resultSlider.querySelector(".slider-counter b");const prev=resultSlider.querySelector(".slider-prev");const next=resultSlider.querySelector(".slider-next");let current=0;let timer;let startX=0;const showSlide=index=>{current=(index+slides.length)%slides.length;slides.forEach((slide,i)=>slide.classList.toggle("active",i===current));dots.forEach((dot,i)=>dot.classList.toggle("active",i===current));if(counter)counter.textContent=String(current+1).padStart(2,"0")};const restart=()=>{clearInterval(timer);timer=setInterval(()=>showSlide(current+1),5000)};prev?.addEventListener("click",()=>{showSlide(current-1);restart()});next?.addEventListener("click",()=>{showSlide(current+1);restart()});dots.forEach((dot,i)=>dot.addEventListener("click",()=>{showSlide(i);restart()}));resultSlider.addEventListener("touchstart",event=>{startX=event.changedTouches[0].clientX},{passive:true});resultSlider.addEventListener("touchend",event=>{const diff=event.changedTouches[0].clientX-startX;if(Math.abs(diff)>45){showSlide(diff>0?current-1:current+1);restart()}},{passive:true});resultSlider.addEventListener("mouseenter",()=>clearInterval(timer));resultSlider.addEventListener("mouseleave",restart);restart()}

const salonSlider=document.querySelector(".salon-slider");if(salonSlider){const slides=[...salonSlider.querySelectorAll(".salon-slide")];const counter=salonSlider.querySelector(".salon-counter b");let current=0;const show=i=>{current=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle("active",n===current));if(counter)counter.textContent=String(current+1).padStart(2,"0")};salonSlider.querySelector(".salon-prev")?.addEventListener("click",()=>show(current-1));salonSlider.querySelector(".salon-next")?.addEventListener("click",()=>show(current+1))}

(()=>{
 const about=document.querySelector('.about');if(about)about.style.display='none';
 const whySection=document.querySelector('.why-us'),reviewsSection=document.querySelector('.real-reviews'),whyGrid=whySection?.querySelector('.why-grid'),reviewCards=reviewsSection?.querySelector('.review-cards');
 if(whyGrid&&reviewCards&&reviewsSection){const compactWhy=whyGrid.cloneNode(true);compactWhy.classList.add('compact-why','visible');compactWhy.classList.remove('reveal');reviewsSection.insertBefore(compactWhy,reviewCards);whySection.style.display='none';const tag=reviewsSection.querySelector('.section-tag');if(tag)tag.textContent='05 / OMDÖMEN & VARFÖR OSS'}
 const contact=document.querySelector('.contact');if(contact)contact.style.display='none';const footerCta=document.querySelector('.footer-cta');if(footerCta)footerCta.style.display='none';const careers=document.querySelector('.careers');if(careers)careers.style.display='none';
 document.querySelectorAll('.nav a[href="#om"],.nav a[href="#jobb"]').forEach(el=>el.remove());
 const footer=document.querySelector('.site-footer');if(footer)footer.id='kontakt';
 const main=document.querySelector('main'),salong=document.querySelector('#salongen'),priser=document.querySelector('#priser'),team=document.querySelector('#teamet'),resultat=document.querySelector('#resultat'),omdomen=document.querySelector('.real-reviews');[salong,priser,team,resultat,omdomen].forEach(section=>{if(section&&main)main.appendChild(section)});
 [['#salongen .section-tag','01 / SALONGEN'],['#priser .section-tag','02 / BEHANDLINGAR & PRISER'],['#teamet .section-tag','03 / MÖT TEAMET'],['#resultat .section-tag','04 / KUNDRESULTAT']].forEach(([selector,text])=>{const el=document.querySelector(selector);if(el)el.textContent=text});
 // Behåll exakt en Jobba hos oss-länk i footern.
 const footerGroups=[...document.querySelectorAll('.footer-group')],footerQuick=footerGroups.find(group=>group.querySelector('h3')?.textContent.trim()==='Snabblänkar');
 const careerLinks=[...document.querySelectorAll('.site-footer a')].filter(a=>a.textContent.toLowerCase().includes('jobba hos oss'));
 careerLinks.slice(1).forEach(a=>a.remove());
 if(footerQuick&&careerLinks.length===0){const link=document.createElement('a');link.className='footer-careers-link';link.href='mailto:kontakt@salongalexander.se?subject=Intresseanmälan%20-%20Jobba%20hos%20Salong%20Alexander';link.textContent='Jobba hos oss ↗';footerQuick.appendChild(link)}
 // Prislistan: gör varje kategori till en enkel accordion på mobil.
 const priceCards=[...document.querySelectorAll('.price-card')];priceCards.forEach((card,i)=>{const title=card.querySelector('h3');if(!title||card.querySelector('.price-toggle'))return;const toggle=document.createElement('button');toggle.type='button';toggle.className='price-toggle';toggle.setAttribute('aria-expanded',i===0?'true':'false');toggle.innerHTML=`<span>${title.textContent}</span><b>${i===0?'−':'+'}</b>`;title.style.display='none';card.insertBefore(toggle,title.nextSibling);if(i!==0)card.classList.add('price-collapsed');toggle.addEventListener('click',()=>{const collapsed=card.classList.toggle('price-collapsed');toggle.setAttribute('aria-expanded',String(!collapsed));toggle.querySelector('b').textContent=collapsed?'+':'−'})});
 const style=document.createElement('style');style.id='customer-first-overrides';style.textContent=`@media (min-width:761px){.section{padding:5.2vw 6vw}.section-tag{margin-bottom:1.7rem}.section-head{margin-bottom:2.3rem}.salon-track,.salon-slide img{height:520px}.result-track,.result-slide img{height:550px}.team-photo{aspect-ratio:4/4.15}.price-toggle{display:none}.price-card h3{display:block!important}}.compact-why{margin-bottom:2.3rem}.compact-why article{min-height:180px;padding:1.4rem}.compact-why article strong{font-size:1.4rem}.compact-why article p{font-size:.88rem;margin-bottom:0}.real-reviews .google-merged-head{margin-top:2.3rem;padding-top:1.8rem}@media(max-width:760px){.section{padding:54px 22px}.section-tag{margin-bottom:1.6rem}.section-head{margin-bottom:2.1rem}.compact-why article{min-height:auto}.price-toggle{width:100%;display:flex;align-items:center;justify-content:space-between;background:none;border:0;color:#fff;padding:.15rem 0 .65rem;text-align:left;font:600 1.25rem Manrope,sans-serif;cursor:pointer}.price-toggle b{color:#f39a3a;font-size:1.55rem;font-weight:400}.price-card.price-collapsed>a{display:none!important}.price-card.price-collapsed{padding-bottom:.7rem}.price-card>a{display:grid!important;grid-template-columns:minmax(0,1fr) auto;gap:.65rem;align-items:center;padding:.72rem 0!important}.price-card>a b,.price-card>a em{display:block!important;margin:0!important}.price-card>a em{text-align:right;white-space:nowrap!important}}`;document.head.appendChild(style)
})();